spring.application.name=ordentrabajoservice

server.port=8083

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-ordenes:3306/ordenes_db?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.user.name=admin
spring.security.user.password=1234

vehiculo.service.url=${VEHICULO_SERVICE_URL:http://vehiculo-service:8080}
mecanico.service.url=${MECANICO_SERVICE_URL:http://mecanico-service:8082}
cliente.service.url=${CLIENTE_SERVICE_URL:http://cliente-service:8081}

# Configuración de Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html