spring.application.name=servicio-service
server.port=8084

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3311/servicio_db?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin123}
spring.jpa.hibernate.ddl-auto=update