spring.application.name=notificacion-service
server.port=8085

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3312/notificacion_db?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin123}
spring.jpa.hibernate.ddl-auto=update