spring.application.name=facturacion-service
server.port=8086

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3313/facturacion_db?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin123}
spring.jpa.hibernate.ddl-auto=update

# Rutas para sus clientes Feign
orden.service.url=${ORDEN_SERVICE_URL:http://ordentrabajoservice:8083}
servicio.service.url=${SERVICIO_SERVICE_URL:http://servicio-service:8084}