spring.application.name=agenda-service
server.port=8083

# Conexión a la Base de Datos (Toma los datos de Docker, y si no, usa el localhost de respaldo)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3310/agenda_db?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin123}
spring.jpa.hibernate.ddl-auto=update

# Ruta para el cliente Feign
cliente.service.url=${CLIENTE_SERVICE_URL:http://cliente-service:8081}